@startuml
title Waveform update task

legend
task_frequency = 20 kHz
wave_steps = 100
end legend

start

partition update_wave() {
:++speed_counter
max_frequency = task_frequency / (2*wave_steps);
if (counter > max_frequency / frequency) then (true)
    :speed_counter = 0;
    :advance step_counter (ramp up/down);
    :compute new output value;
    :amplify and add offset;
else
endif
:return value;
}

:do something with
the output value
(application-specific);

stop
@enduml
