name: Compile apps and documentation

on:
  push:
    branches:
      - "*"
    paths:
      - "doc"
      - "software"

  pull_request:
    branches:
      - "*"
    paths:
      - "doc"
      - "software"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile apps
        uses: ./.github/actions/build
        with:
          directory: software
          target: compile

      - name: Compile documentation
        uses: ./.github/actions/build
        with:
          directory: software
          target: doc
